version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip:
        patterns:
          - "*"
          
  - package-ecosystem: "pip"
    directory: "/.github/workflows/requirements"
    schedule:
      interval: "monthly"
    groups:
      pip:
        patterns:
          - "*"
