version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - libhdf5-dev
    - libblosc-dev

sphinx:
  configuration: doc/source/conf.py

submodules:
  include: all

formats:
  - pdf

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
