version: 2

submodules:
  include: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  apt_packages:
    - libhdf5-dev
    - libblosc-dev

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
